### ISSUE TITLE
如果是左键点击事件触发，则菜单自动销毁了

### ISSUE THREAD

**Issue by Preyou** [lqzhgood/vue-context-menu#2]
我大概跟了下，
![image](https://user-images.githubusercontent.com/36725799/180391840-036aa0d6-53ec-4064-92a7-f849d51e6d3a.png)
鼠标点击时冒泡到了`document`上，所以又立马关闭了。加上`event.stopPropagation()`就好了。

鼠标点击时会同时触发`click`和`mousedown`事件，`prevent`修饰符只阻止了一个事件。

在`nextTick`里注册这些事件，应该可以解决

**Comment by lqzhgood** [comment]
什么叫 _如果是左键点击事件触发，则菜单自动销毁了 ？_

**Comment by Preyou** [comment]
> 什么叫 _如果是左键点击事件触发，则菜单自动销毁了 ？_

这个组件通常是由右键触发的，就像这样
```vue
<div id="app" style="width:100vw;height:100vh" @contextmenu.prevent="onContextmenu"></div>
```
但是如果我改成左键点击触发，则会在创建菜单后立马销毁菜单，给用户的感觉就是根本没有创建。
```vue
<div id="app" style="width:100vw;height:100vh" @click.prevent="onContextmenu"></div>
```

**Comment by lqzhgood** [comment]
这个库设计上就是 `左键` 关闭 `右键` 打开
所有 `左键` 正常事件就是 关闭 操作

**Comment by Preyou** [comment]
> 这个库设计上就是 `左键` 关闭 `右键` 打开 所有 `左键` 正常事件就是 关闭 操作

但是这个功能是可以支持的，而且改一下也很简单，把关闭菜单的监听放到nextTick里注册就好了

**Comment by lqzhgood** [comment]
如果改 右键关闭 左键打开 `click` `mousedown`  `mousewheel`  事件的处理函数是要互换位置的。
这些事件是挂载 document 上， 跟 `nextTick` 无关。你加 .stop 可以，是因为阻止了事件传播到 document，所以事件未生效，并非本义

**Comment by lqzhgood** [comment]
这了用  `mousedown` 应该不妥，应该用 `contextmenu` 的~
有空再捋捋
