### ISSUE TITLE
MenuItemOptions customClass 没有作用

### ISSUE THREAD

**Issue by liang0-0** [lqzhgood/vue-context-menu#3]
想给菜单中的, 单独一个菜单添加菜单项, 但是子菜单中的customClass 添加后没有生效
在浏览器控制台查看元素后发现, class并没有添加上

环境: mac, chrome 都是最新版

<img width="508" alt="image" src="https://github.com/lqzhgood/vue-context-menu/assets/12221912/59d3b600-60fe-4b8a-a772-7eb094d7d6a4">

<img width="814" alt="image" src="https://github.com/lqzhgood/vue-context-menu/assets/12221912/1fd01794-ea04-4a49-b3e7-a3d65fdd00ee">

**Comment by lqzhgood** [comment]
试试原来仓库的吧~
作者又更新了~

https://github.com/GitHub-Laziji/menujs
